# Create to PVs for the data nodes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ndb-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ndb-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
---
apiVersion: mysql.oracle.com/v1alpha1
kind: NdbCluster
metadata:
  name: example-ndb
spec:
  image: mysql/mysql-cluster:8.0.22
  nodeCount: 2
  redundancyLevel: 2
  dataNodePVCSpec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  mysqld:
    nodeCount: 2
