# MySQL Cluster with 2 data nodes, 2 MySQL Servers and Replica 2.
# The NDB Operator will also start 2 Management Nodes as the Replica is 2.
apiVersion: mysql.oracle.com/v1
kind: NdbCluster
metadata:
  name: example-ndb
spec:
  redundancyLevel: 2   # MySQL Cluster Replica
  dataNode:
    nodeCount: 2       # Number of Data Nodes
  mysqlNode:
    nodeCount: 2       # Number of MySQL Servers
