package config

/* From include/mgmapi/mgmapi_config_parameters.h
   Resorted into numeric order in some cases
*/

const CFG_SYS_NAME = 3
const CFG_SYS_PRIMARY_MGM_NODE = 1
const CFG_SYS_CONFIG_GENERATION = 2
const CFG_SYS_PORT_BASE = 8

const CFG_NODE_ID = 3
const CFG_NODE_BYTE_ORDER = 4
const CFG_NODE_HOST = 5
const CFG_NODE_SYSTEM = 6
const CFG_NODE_DATADIR = 7
const CFG_TOTAL_SEND_BUFFER_MEMORY = 9
const CFG_LOCATION_DOMAIN_ID = 10
const CFG_NODE_DEDICATED = 11

const CFG_DB_NO_SAVE_MSGS = 100
const CFG_DB_NO_REPLICAS = 101
const CFG_DB_NO_TABLES = 102
const CFG_DB_NO_ATTRIBUTES = 103
const CFG_DB_NO_TRIGGERS = 105
const CFG_DB_NO_TRANSACTIONS = 106
const CFG_DB_NO_OPS = 107
const CFG_DB_NO_SCANS = 108
const CFG_DB_NO_TRIGGER_OPS = 109
const CFG_DB_NO_INDEX_OPS = 110
const CFG_DB_TRANS_BUFFER_MEM = 111
const CFG_DB_DATA_MEM = 112
const CFG_DB_INDEX_MEM = 113
const CFG_DB_MEMLOCK = 114
const CFG_DB_START_PARTIAL_TIMEOUT = 115
const CFG_DB_START_PARTITION_TIMEOUT = 116
const CFG_DB_START_FAILURE_TIMEOUT = 117
const CFG_DB_HEARTBEAT_INTERVAL = 118
const CFG_DB_API_HEARTBEAT_INTERVAL = 119
const CFG_DB_LCP_INTERVAL = 120
const CFG_DB_GCP_INTERVAL = 121
const CFG_DB_ARBIT_TIMEOUT = 122
const CFG_DB_WATCHDOG_INTERVAL = 123
const CFG_DB_STOP_ON_ERROR = 124
const CFG_DB_FILESYSTEM_PATH = 125
const CFG_DB_NO_REDOLOG_FILES = 126
const CFG_DB_MONITOR = 127
const CFG_DB_MONITOR_PORT = 128
const CFG_DB_TRANSACTION_CHECK_INTERVAL = 129
const CFG_DB_TRANSACTION_INACTIVE_TIMEOUT = 130
const CFG_DB_TRANSACTION_DEADLOCK_TIMEOUT = 131
const CFG_DB_PARALLEL_BACKUPS = 132
const CFG_DB_BACKUP_MEM = 133
const CFG_DB_BACKUP_DATA_BUFFER_MEM = 134
const CFG_DB_BACKUP_LOG_BUFFER_MEM = 135
const CFG_DB_BACKUP_WRITE_SIZE = 136

const CFG_DB_BACKUP_MAX_WRITE_SIZE = 139
const CFG_DB_REDOLOG_FILE_SIZE = 140
const CFG_DB_WATCHDOG_INTERVAL_INITIAL = 141
const CFG_DB_ARBIT_METHOD = 142

const CFG_LOG_DESTINATION = 147
const CFG_DB_DISCLESS = 148
const CFG_DB_NO_ORDERED_INDEXES = 149
const CFG_DB_NO_UNIQUE_HASH_INDEXES = 150
const CFG_DB_NO_LOCAL_OPS = 151
const CFG_DB_NO_LOCAL_SCANS = 152
const CFG_DB_BATCH_SIZE = 153
const CFG_DB_UNDO_INDEX_BUFFER = 154
const CFG_DB_UNDO_DATA_BUFFER = 155
const CFG_DB_REDO_BUFFER = 156
const CFG_DB_LONG_SIGNAL_BUFFER = 157
const CFG_DB_BACKUP_DATADIR = 158
const CFG_DB_MAX_OPEN_FILES = 159
const CFG_DB_DISK_PAGE_BUFFER_MEMORY = 160 /* used from= 5.1 */
const CFG_DB_STRING_MEMORY = 161           /* used from= 5.1 */
const CFG_DB_INITIAL_OPEN_FILES = 162      /* used from= 5.1 */
const CFG_DB_DISK_SYNCH_SIZE = 163

const CFG_DB_MEMREPORT_FREQUENCY = 166
const CFG_DB_BACKUP_REPORT_FREQUENCY = 167
const CFG_DB_O_DIRECT = 168
const CFG_DB_MAX_ALLOCATE = 169
const CFG_DB_MICRO_GCP_INTERVAL = 170 /* micro gcp */
const CFG_DB_MICRO_GCP_TIMEOUT = 171
const CFG_DB_COMPRESSED_BACKUP = 172
const CFG_DB_COMPRESSED_LCP = 173
const CFG_DB_SCHED_EXEC_TIME = 174
const CFG_DB_SCHED_SPIN_TIME = 175
const CFG_DB_REALTIME_SCHEDULER = 176
const CFG_DB_EXECUTE_LOCK_CPU = 177
const CFG_DB_MAINT_LOCK_CPU = 178
const CFG_DB_SUBSCRIPTIONS = 179
const CFG_DB_SUBSCRIBERS = 180
const CFG_DB_SUB_OPERATIONS = 181
const CFG_DB_MAX_BUFFERED_EPOCHS = 182
const CFG_DB_SUMA_HANDOVER_TIMEOUT = 183
const CFG_DB_STARTUP_REPORT_FREQUENCY = 184
const CFG_DB_NODEGROUP = 185
const CFG_DB_MT_THREADS = 186
const CFG_NDBMT_LQH_THREADS = 187
const CFG_NDBMT_LQH_WORKERS = 188
const CFG_DB_INIT_REDO = 189
const CFG_DB_THREAD_POOL = 190
const CFG_NDBMT_CLASSIC = 191

const CFG_DB_DD_FILESYSTEM_PATH = 193
const CFG_DB_DD_DATAFILE_PATH = 194
const CFG_DB_DD_UNDOFILE_PATH = 195
const CFG_DB_DD_LOGFILEGROUP_SPEC = 196
const CFG_DB_DD_TABLEPACE_SPEC = 197
const CFG_DB_SGA = 198 /* super pool mem */

const CFG_DB_LCP_TRY_LOCK_TIMEOUT = 605
const CFG_DB_MT_BUILD_INDEX = 606
const CFG_DB_HB_ORDER = 607
const CFG_DB_DICT_TRACE = 608
const CFG_DB_MAX_START_FAIL = 609        /* For StopOnError=0 */
const CFG_DB_START_FAIL_DELAY_SECS = 610 /* For StopOnError=0 */
const CFG_DB_REDO_OVERCOMMIT_LIMIT = 611
const CFG_DB_REDO_OVERCOMMIT_COUNTER = 612
const CFG_DB_EVENTLOG_BUFFER_SIZE = 613
const CFG_DB_NUMA = 614
const CFG_DB_LATE_ALLOC = 615
const CFG_DB_2PASS_INR = 616
const CFG_DB_PARALLEL_SCANS_PER_FRAG = 617
const CFG_DB_CONNECT_CHECK_DELAY = 618
const CFG_DB_START_NO_NODEGROUP_TIMEOUT = 619
const CFG_DB_INDEX_STAT_AUTO_CREATE = 620
const CFG_DB_INDEX_STAT_AUTO_UPDATE = 621
const CFG_DB_INDEX_STAT_SAVE_SIZE = 622
const CFG_DB_INDEX_STAT_SAVE_SCALE = 623
const CFG_DB_INDEX_STAT_TRIGGER_PCT = 624
const CFG_DB_INDEX_STAT_TRIGGER_SCALE = 625
const CFG_DB_INDEX_STAT_UPDATE_DELAY = 626
const CFG_DB_MAX_DML_OPERATIONS_PER_TRANSACTION = 627
const CFG_DB_MT_THREAD_CONFIG = 628
const CFG_DB_CRASH_ON_CORRUPTED_TUPLE = 629
const CFG_DB_FREE_PCT = 630
const CFG_DB_LCP_SCAN_WATCHDOG_LIMIT = 631
const CFG_DB_NO_REDOLOG_PARTS = 632

const CFG_DB_AT_RESTART_SKIP_INDEXES = 633
const CFG_DB_AT_RESTART_SKIP_FKS = 634
const CFG_DB_SERVER_PORT = 635
const CFG_DB_TCPBIND_INADDR_ANY = 636
const CFG_DB_AT_RESTART_SUBSCRIBER_CONNECT_TIMEOUT = 637
const CFG_DB_MIN_DISK_WRITE_SPEED = 638
const CFG_DB_MAX_DISK_WRITE_SPEED = 639
const CFG_DB_MAX_DISK_WRITE_SPEED_OTHER_NODE_RESTART = 640
const CFG_DB_MAX_DISK_WRITE_SPEED_OWN_RESTART = 641
const CFG_MIXOLOGY_LEVEL = 642
const CFG_DB_PARALLEL_COPY_THREADS = 643
const CFG_DB_MAX_SEND_DELAY = 644
const CFG_DB_BACKUP_DISK_WRITE_PCT = 645
const CFG_DB_SCHED_RESPONSIVENESS = 646
const CFG_DB_SCHED_SCAN_PRIORITY = 647
const CFG_DB_DISK_DATA_FORMAT = 648
const CFG_DB_ENABLE_PARTIAL_LCP = 649
const CFG_DB_O_DIRECT_SYNC_FLAG = 650
const CFG_DB_UI_BUILD_MAX_BATCHSIZE = 651
const CFG_DB_FK_BUILD_MAX_BATCHSIZE = 652
const CFG_DB_REORG_BUILD_MAX_BATCHSIZE = 653
const CFG_DB_RECOVERY_WORK = 654
const CFG_DB_USE_SHM = 655
const CFG_DB_INSERT_RECOVERY_WORK = 656
const CFG_DB_WATCHDOG_IMMEDIATE_KILL = 657
const CFG_DB_ENABLE_REDO_CONTROL = 658
const CFG_DB_ENABLE_MT_BACKUP = 659
const CFG_DB_RESERVED_INDEX_OPS = 660
const CFG_DB_RESERVED_TRIGGER_OPS = 661
const CFG_DB_RESERVED_OPS = 662
const CFG_DB_RESERVED_LOCAL_SCANS = 663
const CFG_DB_RESERVED_TRANSACTIONS = 664
const CFG_DB_RESERVED_SCANS = 665
const CFG_DB_RESERVED_TRANS_BUFFER_MEM = 666
const CFG_DB_TRANSACTION_MEM = 667
const CFG_DB_MAX_DD_LATENCY = 668
const CFG_DB_DD_USING_SAME_DISK = 669
const CFG_DB_NODE_GROUP_TRANSPORTERS = 670
const CFG_DB_SPIN_METHOD = 671
const CFG_DB_SPIN_TIME_PER_CALL = 672
const CFG_DB_REQUIRE_ENCRYPTED_BACKUP = 673
const CFG_DB_PARTITIONS_PER_NODE = 674
const CFG_DB_CLASSIC_FRAGMENTATION = 675
const CFG_DB_NUM_CPUS = 676
const CFG_DB_AUTO_THREAD_CONFIG = 677

const CFG_NODE_ARBIT_RANK = 200
const CFG_NODE_ARBIT_DELAY = 201
const CFG_EXTRA_SEND_BUFFER_MEMORY = 203
const CFG_MGMD_MGMD_HEARTBEAT_INTERVAL = 204
const CFG_DB_DISK_PAGE_BUFFER_ENTRIES = 205
const CFG_DB_GCP_TIMEOUT = 206

const CFG_MIN_LOGLEVEL = 250
const CFG_LOGLEVEL_STARTUP = 250
const CFG_LOGLEVEL_SHUTDOWN = 251
const CFG_LOGLEVEL_STATISTICS = 252
const CFG_LOGLEVEL_CHECKPOINT = 253
const CFG_LOGLEVEL_NODERESTART = 254
const CFG_LOGLEVEL_CONNECTION = 255
const CFG_LOGLEVEL_INFO = 256
const CFG_LOGLEVEL_WARNING = 257
const CFG_LOGLEVEL_ERROR = 258
const CFG_LOGLEVEL_CONGESTION = 259
const CFG_LOGLEVEL_DEBUG = 260
const CFG_LOGLEVEL_BACKUP = 261
const CFG_LOGLEVEL_SCHEMA = 262
const CFG_MAX_LOGLEVEL = 262

const CFG_MGM_PORT = 300

const CFG_DB_MAX_BUFFERED_EPOCH_BYTES = 350

const CFG_CONNECTION_NODE_1 = 400
const CFG_CONNECTION_NODE_2 = 401
const CFG_CONNECTION_SEND_SIGNAL_ID = 402
const CFG_CONNECTION_CHECKSUM = 403
const CFG_CONNECTION_NODE_1_SYSTEM = 404
const CFG_CONNECTION_NODE_2_SYSTEM = 405
const CFG_CONNECTION_SERVER_PORT = 406
const CFG_CONNECTION_HOSTNAME_1 = 407
const CFG_CONNECTION_HOSTNAME_2 = 408
const CFG_CONNECTION_GROUP = 409
const CFG_CONNECTION_NODE_ID_SERVER = 410
const CFG_CONNECTION_OVERLOAD = 411
const CFG_CONNECTION_PRESEND_CHECKSUM = 412
const CFG_CONNECTION_UNRES_HOSTS = 413

const CFG_TCP_SERVER = 452
const CFG_TCP_SEND_BUFFER_SIZE = 454
const CFG_TCP_RECEIVE_BUFFER_SIZE = 455
const CFG_TCP_PROXY = 456
const CFG_TCP_RCV_BUF_SIZE = 457
const CFG_TCP_SND_BUF_SIZE = 458
const CFG_TCP_MAXSEG_SIZE = 459
const CFG_TCP_BIND_INADDR_ANY = 460
const CFG_TCP_SPINTIME = 461

const CFG_SHM_SEND_SIGNAL_ID = 500
const CFG_SHM_CHECKSUM = 501
const CFG_SHM_KEY = 502
const CFG_SHM_BUFFER_MEM = 503
const CFG_SHM_SPINTIME = 505
const CFG_SHM_SEND_BUFFER_SIZE = 506

const CFG_MAX_SCAN_BATCH_SIZE = 800
const CFG_BATCH_BYTE_SIZE = 801
const CFG_BATCH_SIZE = 802
const CFG_AUTO_RECONNECT = 803
const CFG_HB_THREAD_PRIO = 804
const CFG_DEFAULT_OPERATION_REDO_PROBLEM_ACTION = 805
const CFG_DEFAULT_HASHMAP_SIZE = 806
const CFG_CONNECT_BACKOFF_MAX_TIME = 807
const CFG_START_CONNECT_BACKOFF_MAX_TIME = 808
const CFG_API_VERBOSE = 809

const CFG_DB_STOP_ON_ERROR_INSERT = 1

const CFG_TYPE_OF_SECTION = 999
const CFG_SECTION_SYSTEM = 1000
const CFG_SECTION_NODE = 2000
const CFG_SECTION_CONNECTION = 3000

const NODE_TYPE_DB = 0
const NODE_TYPE_API = 1
const NODE_TYPE_MGM = 2

const CONNECTION_TYPE_TCP = 0
const CONNECTION_TYPE_SHM = 1

const ARBIT_METHOD_DISABLED = 0
const ARBIT_METHOD_DEFAULT = 1
const ARBIT_METHOD_WAITEXTERNAL = 2

const OPERATION_REDO_PROBLEM_ACTION_ABORT = 0
const OPERATION_REDO_PROBLEM_ACTION_QUEUE = 1
